### ISSUE TITLE
Failed to create CloudFormation stack for the Fargate service: Assign public IP is not supported for this launch type.

### ISSUE THREAD

**Issue by vankeer** [nathanpeck/socket.io-chat-fargate#3]
When I try to create a new CloudFormation stack with https://github.com/nathanpeck/socket.io-chat-fargate/blob/3-deployment/recipes/public-service.yml I get a `CREATE_FAILED` with the error `Assign public IP is not supported for this launch type.`.

So, I deleted the line `AssignPublicIp: ENABLED` from the AWS::ECS::Service config. When I try to deploy again, the creation process is stuck for the service (same when I switch the value to DISABLED).

My setup is the same as in the tutorial and I'm pretty sure I didn't miss a step.

Any hints?

Thank you!

**Comment by nathanpeck** [comment]
The deployment process has been updated pretty extensively. Please take another look through the deploy docs in this repo and give it another try. I don't think you'll run into this error now.
